name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'  # Specify Node.js version 16.x

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to FTP
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USER: ${{ secrets.FTP_USER }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        sudo apt-get install -y lftp
        lftp -u $FTP_USER,$FTP_PASSWORD $FTP_SERVER -e "
        set ssl:verify-certificate no;
        mirror -R -P 5 ./dist /;
        bye
        "
